### ISSUE TITLE
Error Sign In Failed

### ISSUE THREAD

**Issue by iheind** [apgapg/connectit_app#2]
hello, 
why i get error  ⛔ PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiExcep
tion: 10: , null, null)

**Comment by apgapg** [comment]
Fot Google signin you need to add SHA to the project wither in firebase or cloud console. Only then you can do signin in your case.

**Comment by iheind** [comment]
hi @apgapg , thankyou for answer. 
i have been add SHA fingerprint in firebase, then download google-services.json again. and replace in folder android/app. but still getting error PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiExcep
tion: 10: , null, null) :(

flutter doctor
![Capture](https://user-images.githubusercontent.com/70085985/98645200-34889480-2364-11eb-9947-422f018cc4ca.PNG)

**Comment by apgapg** [comment]
Did you enable google sign in in authentication tab on firebase?

**Comment by iheind** [comment]
i have
![Capture2](https://user-images.githubusercontent.com/70085985/98665620-84745500-237e-11eb-8762-8c5c686dfaff.PNG)

**Comment by iheind** [comment]
for cloud firestore, whether to make a collection?
![Capture3](https://user-images.githubusercontent.com/70085985/98666143-2b58f100-237f-11eb-8886-297ef144d1e8.PNG)

**Comment by iheind** [comment]
`Parameter format not correct -
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\ihein\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4+2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\ihein\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-1.6.0\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.`

**Comment by iheind** [comment]
problem solved, i regenerated sha-1. thank you my friend.

**Comment by iheind** [comment]
problem solved, i regenerated sha-1. thank you my friend.
